- name: Deploy rannasta-suomeen
  hosts: server_main
  vars_files:
    - vault/vault.yml
  become_user: "{{user}}"
  become: true
  tasks:
    - name: Deploy db
      include_tasks: ./tasks/deploy-db.yml
      vars:
        - image: ghcr.io/rannasta-suomeen/rannasta-suomeen-sdk:release
        - service_name: docker.rs-db
        - port: 5432

    - name: Deploy frontend
      include_tasks: ./tasks/deploy-frontend.yml
      vars:
        - image: ghcr.io/rannasta-suomeen/rannasta-suomeen-rs:release
        - service_name: docker.rs-frontend
        - port: 3030

        # sha256:af79128118708aa80e6b4d2a0c3779a7f3ee01bbdaa4ae7f1a3f16ebab6729f9